"""Seed content for Sparsh Pehla — services, blogs, testimonials, faqs, gallery."""

SERVICES = [
    {
        "slug": "family-counselling",
        "title": "Family Counselling",
        "icon": "HeartHandshake",
        "image": "family_counselling",
        "tagline": "Nurturing harmony as your family grows",
        "short_description": "Compassionate guidance for couples and families navigating the beautiful, complex transition into parenthood.",
        "hero_description": "Welcoming a child reshapes every relationship in a home. Our gentle, judgement-free counselling helps couples and families communicate, heal, and grow together.",
        "story": "Becoming parents is one of life's most profound shifts. Amid the joy, there can be unspoken worries, changing dynamics, and emotional fatigue. At Sparsh Pehla, our family counselling creates a safe, warm space where every voice is heard. Through mindful conversation and proven therapeutic tools, we help you strengthen your bond and step into parenthood as a united, supported family.",
        "benefits": [
            "Stronger communication between partners",
            "Tools to navigate stress and emotional change",
            "A safe space to share fears without judgement",
            "Guidance for involving grandparents and family",
        ],
        "who_for": [
            "Expecting couples preparing for parenthood",
            "Families adjusting to a new baby",
            "Parents experiencing relationship strain",
            "Anyone seeking emotional clarity during pregnancy",
        ],
        "process": [
            {"title": "Gentle Intake", "desc": "We listen to understand your family's unique story and needs."},
            {"title": "Personalised Plan", "desc": "A tailored counselling roadmap built around your goals."},
            {"title": "Guided Sessions", "desc": "Warm, structured sessions in person or online."},
            {"title": "Ongoing Support", "desc": "Continued check-ins as your family evolves."},
        ],
        "faqs": [
            {"q": "Are sessions confidential?", "a": "Absolutely. Every conversation is private and held in complete confidence."},
            {"q": "Can we attend as a couple?", "a": "Yes, we offer individual, couple, and whole-family sessions."},
            {"q": "Do you offer online counselling?", "a": "We do — sessions are available both in person and virtually."},
        ],
    },
    {
        "slug": "garbh-sanskar",
        "title": "Garbh Sanskar",
        "icon": "Flower2",
        "image": "garbh_sanskar",
        "tagline": "Ancient wisdom for a serene pregnancy",
        "short_description": "A holistic blend of meditation, music, and mindful practices that nurture your baby's well-being from the womb.",
        "hero_description": "Rooted in timeless Indian tradition, Garbh Sanskar nurtures the deep bond between mother and child through positivity, sound, and mindful living.",
        "story": "Garbh Sanskar is the beautiful belief that a child's emotional and spiritual journey begins in the womb. Our programme weaves together soothing music, guided meditation, affirmations, and gentle rituals designed to fill your pregnancy with calm and connection. Each session is an invitation to slow down, breathe, and shower your growing baby with love.",
        "benefits": [
            "Deeper emotional bonding with your baby",
            "Reduced stress through meditation and music",
            "A positive, peaceful pregnancy mindset",
            "Mindful daily routines rooted in tradition",
        ],
        "who_for": [
            "Expecting mothers in any trimester",
            "Couples wishing to bond with their baby",
            "Those seeking a spiritual pregnancy experience",
            "Mothers wanting calm and positivity",
        ],
        "process": [
            {"title": "Trimester Assessment", "desc": "We align practices with your stage of pregnancy."},
            {"title": "Daily Rituals", "desc": "Personalised meditation, music, and reading routines."},
            {"title": "Guided Sessions", "desc": "Weekly sessions to deepen your practice."},
            {"title": "Birth Preparation", "desc": "Mindful tools for a calm, confident delivery."},
        ],
        "faqs": [
            {"q": "When should I start Garbh Sanskar?", "a": "It can begin at any stage, though early pregnancy offers the fullest benefit."},
            {"q": "Is this a religious programme?", "a": "It is spiritual and inclusive — open to families of all beliefs."},
            {"q": "Can my partner join?", "a": "Yes, partner participation deepens the bonding experience."},
        ],
    },
    {
        "slug": "pregnancy-yoga",
        "title": "Yoga by Certified Instructor",
        "icon": "PersonStanding",
        "image": "yoga",
        "tagline": "Gentle movement for body and breath",
        "short_description": "Safe, government-certified prenatal and postnatal yoga to keep you strong, flexible, and centred.",
        "hero_description": "Guided by a government-certified instructor, our prenatal yoga nurtures strength, ease, and breath for every stage of your journey.",
        "story": "Yoga during pregnancy is a gift to both body and mind. Our certified instructor designs each flow to ease common discomforts, build the strength you'll need for birth, and connect you to your breath. Every posture is adapted to your trimester and ability, in a warm, unhurried setting that honours your changing body.",
        "benefits": [
            "Relief from back pain and pregnancy discomfort",
            "Improved strength, flexibility, and posture",
            "Calming breathwork for labour and beyond",
            "Better sleep and reduced anxiety",
        ],
        "who_for": [
            "Expecting mothers at any trimester",
            "New mothers seeking postnatal recovery",
            "Beginners with no prior yoga experience",
            "Anyone wanting safe, certified guidance",
        ],
        "process": [
            {"title": "Health Check", "desc": "A gentle assessment of your fitness and needs."},
            {"title": "Tailored Flow", "desc": "Trimester-appropriate sequences designed for you."},
            {"title": "Guided Practice", "desc": "Small-group or private certified sessions."},
            {"title": "Breath & Birth Prep", "desc": "Breathing techniques to support labour."},
        ],
        "faqs": [
            {"q": "Is prenatal yoga safe?", "a": "Yes — every session is certified, supervised, and adapted to your stage."},
            {"q": "I've never done yoga before. Can I join?", "a": "Absolutely. Our classes welcome complete beginners."},
            {"q": "When can I start postnatal yoga?", "a": "Typically after your doctor's clearance, around 6 weeks postpartum."},
        ],
    },
    {
        "slug": "pre-shopping",
        "title": "Pre Shopping for Mom & Baby",
        "icon": "ShoppingBag",
        "image": "pre_shopping",
        "tagline": "Thoughtfully prepared for the big day",
        "short_description": "Curated guidance to prepare your home and hospital bag with everything mom and baby truly need.",
        "hero_description": "From the hospital bag to the nursery, we help you choose only what truly matters — calm, curated, and clutter-free.",
        "story": "The world of baby products can feel overwhelming. Our pre-shopping service brings clarity and calm, helping you select premium, practical essentials for both mother and baby. We share curated checklists, trusted recommendations, and gentle guidance so you feel fully prepared — without the overwhelm.",
        "benefits": [
            "Expert-curated checklists for mom and baby",
            "Avoid overspending on unnecessary items",
            "Confidence that you're fully prepared",
            "Premium, trusted product recommendations",
        ],
        "who_for": [
            "First-time parents unsure where to start",
            "Busy parents wanting a curated approach",
            "Families planning a nursery",
            "Anyone preparing a hospital bag",
        ],
        "process": [
            {"title": "Needs Discovery", "desc": "We learn your lifestyle, budget, and preferences."},
            {"title": "Curated Lists", "desc": "Personalised essentials for every stage."},
            {"title": "Shopping Guidance", "desc": "Trusted brands and where to find them."},
            {"title": "Final Check", "desc": "A reassuring review before your due date."},
        ],
        "faqs": [
            {"q": "Do you sell the products?", "a": "We provide independent, unbiased guidance and curated recommendations."},
            {"q": "Can you work within my budget?", "a": "Yes, every list is tailored to your budget and needs."},
            {"q": "When should we start?", "a": "Ideally in the second trimester, with a final check near your due date."},
        ],
    },
    {
        "slug": "pre-maternity-photography",
        "title": "Pre-Maternity Photography",
        "icon": "Camera",
        "image": "photography",
        "tagline": "Capturing the glow of motherhood",
        "short_description": "Elegant, cinematic maternity portraits that celebrate this fleeting, beautiful chapter of your life.",
        "hero_description": "Soft light, timeless frames, and genuine emotion — artistic maternity portraits you'll treasure forever.",
        "story": "Pregnancy is a season of radiant beauty that deserves to be remembered. Our maternity photography sessions are unhurried and intimate, crafted to capture the glow, the anticipation, and the love. With cinematic lighting and tasteful styling, we create heirloom-quality portraits that tell your story.",
        "benefits": [
            "Timeless, editorial-quality maternity portraits",
            "Relaxed, guided sessions for natural emotion",
            "Professional styling and lighting",
            "Beautiful keepsakes for your family",
        ],
        "who_for": [
            "Expecting mothers in their third trimester",
            "Couples wishing to capture this milestone",
            "Families wanting heirloom portraits",
            "Anyone celebrating their pregnancy journey",
        ],
        "process": [
            {"title": "Consultation", "desc": "We plan your vision, wardrobe, and location."},
            {"title": "Styling", "desc": "Guidance on outfits and looks that flatter."},
            {"title": "The Session", "desc": "A relaxed, beautifully directed photoshoot."},
            {"title": "Curated Gallery", "desc": "Hand-edited images delivered to keep forever."},
        ],
        "faqs": [
            {"q": "When is the best time for a shoot?", "a": "Usually between 28-34 weeks, when your bump is beautifully round."},
            {"q": "Can my partner and children join?", "a": "Of course — family portraits make the session even more special."},
            {"q": "Where do shoots take place?", "a": "In our studio, your home, or a chosen outdoor location."},
        ],
    },
    {
        "slug": "baby-massage",
        "title": "Indian Baby Massage & Bath",
        "icon": "Baby",
        "image": "baby_massage",
        "tagline": "The timeless ritual of touch",
        "short_description": "Traditional Indian massage and bath techniques that soothe your baby and deepen your bond.",
        "hero_description": "Learn the gentle, time-honoured art of malish and bathing — nurturing your baby's growth, sleep, and connection.",
        "story": "For generations, Indian families have understood the healing power of loving touch. Our baby massage and bath guidance teaches you authentic malish techniques using safe oils, along with calming bath rituals. These practices support your baby's circulation, digestion, and sleep — while creating precious moments of bonding.",
        "benefits": [
            "Soothes baby and improves sleep",
            "Supports digestion and circulation",
            "Strengthens parent-baby bonding",
            "Authentic, safe traditional techniques",
        ],
        "who_for": [
            "New parents of newborns and infants",
            "Families wanting traditional techniques",
            "Parents seeking better baby sleep",
            "Grandparents and caregivers",
        ],
        "process": [
            {"title": "Demonstration", "desc": "Hands-on guidance with safe oils and strokes."},
            {"title": "Practice Together", "desc": "You practise gently with expert support."},
            {"title": "Bath Ritual", "desc": "Calming, safe bathing techniques explained."},
            {"title": "Routine Building", "desc": "Creating a soothing daily ritual."},
        ],
        "faqs": [
            {"q": "What oils are safe for my baby?", "a": "We recommend gentle, natural oils suited to your baby's skin."},
            {"q": "When can I start massaging my baby?", "a": "Gentle massage can usually begin a few weeks after birth."},
            {"q": "Can fathers learn too?", "a": "Yes — we encourage all caregivers to participate."},
        ],
    },
    {
        "slug": "pregnancy-wellness",
        "title": "Pregnancy Wellness Programs",
        "icon": "Sparkles",
        "image": "wellness_program",
        "tagline": "Holistic care for every trimester",
        "short_description": "Comprehensive wellness programmes blending nutrition, movement, and emotional care throughout pregnancy.",
        "hero_description": "A complete, trimester-by-trimester wellness journey caring for your body, mind, and spirit.",
        "story": "Every pregnancy is unique, and so is every mother's wellness journey. Our programmes bring together nutrition guidance, gentle movement, emotional support, and mindful practices into one nurturing path. We walk beside you through each trimester, adapting care to your evolving needs so you feel strong, supported, and serene.",
        "benefits": [
            "Personalised nutrition and movement plans",
            "Emotional and mental well-being support",
            "Trimester-specific care and education",
            "A dedicated wellness companion throughout",
        ],
        "who_for": [
            "Expecting mothers seeking holistic care",
            "First-time mothers wanting full support",
            "Those with specific wellness goals",
            "Mothers wanting a structured journey",
        ],
        "process": [
            {"title": "Wellness Assessment", "desc": "Understanding your health, goals, and needs."},
            {"title": "Custom Programme", "desc": "A holistic plan tailored to your trimester."},
            {"title": "Guided Journey", "desc": "Regular sessions and ongoing adjustments."},
            {"title": "Birth & Beyond", "desc": "Preparation for delivery and early motherhood."},
        ],
        "faqs": [
            {"q": "How long is the programme?", "a": "Programmes can span a single trimester or your full pregnancy."},
            {"q": "Is nutrition guidance included?", "a": "Yes, personalised nutrition is a core part of every programme."},
            {"q": "Can I join in my third trimester?", "a": "Absolutely — we tailor care to whatever stage you're in."},
        ],
    },
    {
        "slug": "mother-care",
        "title": "Mother Care Support",
        "icon": "Heart",
        "image": "mother_care",
        "tagline": "Because mothers deserve care too",
        "short_description": "Dedicated postnatal support helping new mothers rest, heal, and thrive in the fourth trimester.",
        "hero_description": "In the tender weeks after birth, we surround you with the care, rest, and reassurance you deserve.",
        "story": "So much attention turns to the baby that mothers are often left to fend for themselves. Sparsh Pehla's mother care support changes that. We provide nurturing guidance on rest, recovery, nutrition, and emotional well-being — ensuring you are held, healed, and cared for during the precious, demanding fourth trimester.",
        "benefits": [
            "Restorative recovery and rest guidance",
            "Nourishing postnatal nutrition support",
            "Emotional reassurance and check-ins",
            "Practical help adjusting to motherhood",
        ],
        "who_for": [
            "New mothers in the postpartum period",
            "Mothers recovering from delivery",
            "Those feeling overwhelmed or fatigued",
            "Families wanting to support new mums",
        ],
        "process": [
            {"title": "Postnatal Check-in", "desc": "Understanding your recovery and well-being."},
            {"title": "Care Plan", "desc": "Rest, nutrition, and emotional support tailored to you."},
            {"title": "Ongoing Support", "desc": "Regular nurturing check-ins."},
            {"title": "Confidence Building", "desc": "Empowering you in your new role."},
        ],
        "faqs": [
            {"q": "When does mother care begin?", "a": "Ideally right after birth, through the first weeks postpartum."},
            {"q": "Do you offer home support?", "a": "Yes, we offer both home and virtual support options."},
            {"q": "Can this help with baby blues?", "a": "We provide emotional support and guidance, and refer onward when needed."},
        ],
    },
    {
        "slug": "newborn-guidance",
        "title": "Newborn Guidance",
        "icon": "Moon",
        "image": "newborn",
        "tagline": "Confident care from day one",
        "short_description": "Expert support for the early days — feeding, sleep, soothing, and understanding your newborn.",
        "hero_description": "Those first days can feel daunting. We gently guide you through feeding, sleep, and soothing with calm expertise.",
        "story": "A newborn arrives without a manual, and the early days are full of questions. Our newborn guidance gives you trusted, reassuring answers — from understanding hunger cues and sleep rhythms to soothing techniques and safe routines. We help you read your baby with confidence, turning uncertainty into joyful connection.",
        "benefits": [
            "Confidence in feeding and soothing",
            "Understanding sleep and hunger cues",
            "Safe, gentle daily routines",
            "Reassurance from caring experts",
        ],
        "who_for": [
            "First-time parents of newborns",
            "Parents feeling unsure or anxious",
            "Families wanting expert reassurance",
            "Caregivers supporting new parents",
        ],
        "process": [
            {"title": "Newborn Assessment", "desc": "Understanding your baby and your concerns."},
            {"title": "Guided Support", "desc": "Practical help with feeding, sleep, and care."},
            {"title": "Routine Setup", "desc": "Gentle rhythms that suit your family."},
            {"title": "Follow-up", "desc": "Continued guidance as your baby grows."},
        ],
        "faqs": [
            {"q": "Can you help with night feeds?", "a": "Yes, we guide you on feeding rhythms day and night."},
            {"q": "Is this suitable for premature babies?", "a": "We tailor guidance carefully and coordinate with your paediatrician."},
            {"q": "How soon can we start?", "a": "Support is available from the very first days after birth."},
        ],
    },
    {
        "slug": "emotional-wellness",
        "title": "Emotional Wellness for Parents",
        "icon": "Brain",
        "image": "emotional_wellness",
        "tagline": "Caring for the heart of parenthood",
        "short_description": "Compassionate emotional support helping parents navigate the feelings that come with raising a child.",
        "hero_description": "Parenthood stirs deep emotions. We offer a safe, warm space to process, heal, and find balance.",
        "story": "The emotional landscape of parenthood is vast — joy, exhaustion, worry, love. Our emotional wellness support gives parents a compassionate space to be heard. Through mindful conversation and gentle techniques, we help you manage stress, process change, and reconnect with yourself, so you can parent from a place of calm and strength.",
        "benefits": [
            "A safe space to process emotions",
            "Tools for managing stress and overwhelm",
            "Support for parental anxiety",
            "Renewed balance and self-connection",
        ],
        "who_for": [
            "New and expecting parents",
            "Parents feeling overwhelmed or anxious",
            "Those navigating major life change",
            "Anyone seeking emotional balance",
        ],
        "process": [
            {"title": "Listening Session", "desc": "We begin by truly hearing your experience."},
            {"title": "Personalised Support", "desc": "Gentle techniques matched to your needs."},
            {"title": "Guided Practice", "desc": "Mindfulness and coping tools you can use daily."},
            {"title": "Ongoing Care", "desc": "Continued support as you grow."},
        ],
        "faqs": [
            {"q": "Is this therapy?", "a": "We offer supportive guidance and refer to clinical care when needed."},
            {"q": "Can both parents attend?", "a": "Yes, individual and joint sessions are available."},
            {"q": "Are sessions private?", "a": "Completely — your privacy is always protected."},
        ],
    },
    {
        "slug": "parenting-workshops",
        "title": "Parenting Workshops",
        "icon": "Users",
        "image": "parenting_workshop",
        "tagline": "Learn, share, and grow together",
        "short_description": "Interactive workshops where parents gain practical skills and connect with a supportive community.",
        "hero_description": "Engaging, expert-led workshops that build confident parents and a warm community of families.",
        "story": "Parenting is easier when we learn together. Our workshops bring families into a warm, welcoming space to gain practical skills and share experiences. From feeding and sleep to communication and play, each session blends expert insight with genuine connection — leaving you informed, inspired, and part of a community.",
        "benefits": [
            "Practical, expert-led parenting skills",
            "A supportive community of parents",
            "Interactive, engaging learning",
            "Confidence in everyday parenting",
        ],
        "who_for": [
            "Expecting and new parents",
            "Parents wanting practical skills",
            "Those seeking community connection",
            "Caregivers and grandparents",
        ],
        "process": [
            {"title": "Choose a Topic", "desc": "Select workshops that match your needs."},
            {"title": "Interactive Session", "desc": "Hands-on learning led by experts."},
            {"title": "Group Sharing", "desc": "Connect and learn with other families."},
            {"title": "Take-home Tools", "desc": "Practical resources to use at home."},
        ],
        "faqs": [
            {"q": "Are workshops in groups?", "a": "Yes, they're interactive group sessions — private options are available too."},
            {"q": "What topics do you cover?", "a": "Feeding, sleep, play, communication, safety, and more."},
            {"q": "Can I attend with my partner?", "a": "Absolutely, partners and caregivers are welcome."},
        ],
    },
    {
        "slug": "lactation-guidance",
        "title": "Lactation Guidance",
        "icon": "Droplet",
        "image": "lactation",
        "tagline": "Supporting your feeding journey",
        "short_description": "Patient, expert lactation support helping you and your baby find a comfortable feeding rhythm.",
        "hero_description": "Whatever your feeding journey looks like, we offer gentle, knowledgeable support every step of the way.",
        "story": "Feeding your baby can be one of the most rewarding — and challenging — parts of early motherhood. Our lactation guidance offers patient, judgement-free support with latching, positioning, supply, and comfort. We meet you where you are, helping you and your baby find a feeding rhythm that feels right for you both.",
        "benefits": [
            "Help with latching and positioning",
            "Support for milk supply concerns",
            "Relief from feeding discomfort",
            "Confidence in your feeding journey",
        ],
        "who_for": [
            "New mothers beginning to breastfeed",
            "Those facing latching or supply issues",
            "Mothers experiencing feeding discomfort",
            "Anyone seeking feeding reassurance",
        ],
        "process": [
            {"title": "Feeding Assessment", "desc": "Understanding your concerns and goals."},
            {"title": "Hands-on Guidance", "desc": "Support with latch, positioning, and comfort."},
            {"title": "Personalised Plan", "desc": "A feeding plan that works for you."},
            {"title": "Follow-up Support", "desc": "Continued check-ins as you progress."},
        ],
        "faqs": [
            {"q": "What if I can't breastfeed?", "a": "We support all feeding choices without judgement, including combination feeding."},
            {"q": "Can you help with low supply?", "a": "Yes, we offer guidance and practical strategies for supply concerns."},
            {"q": "When should I seek help?", "a": "As early as possible — early support makes a real difference."},
        ],
    },
    {
        "slug": "postpartum-recovery",
        "title": "Postpartum Recovery Guidance",
        "icon": "Leaf",
        "image": "postpartum",
        "tagline": "Healing gently, one day at a time",
        "short_description": "Holistic guidance to help your body and mind recover and rebuild strength after birth.",
        "hero_description": "Recovery is a journey, not a race. We guide your healing with gentle movement, nourishment, and rest.",
        "story": "Your body has done something extraordinary, and recovery deserves patience and care. Our postpartum recovery guidance combines gentle restorative movement, nourishing nutrition, and emotional support to help you rebuild strength safely. We honour your pace, supporting your whole self as you heal into your new chapter.",
        "benefits": [
            "Safe, gentle restorative movement",
            "Nourishing recovery nutrition",
            "Rebuilding core and pelvic strength",
            "Emotional support through healing",
        ],
        "who_for": [
            "Mothers recovering after delivery",
            "Those healing from C-section",
            "Mothers rebuilding strength safely",
            "Anyone navigating the fourth trimester",
        ],
        "process": [
            {"title": "Recovery Assessment", "desc": "Understanding your birth and healing needs."},
            {"title": "Gentle Plan", "desc": "Safe movement and nutrition tailored to you."},
            {"title": "Guided Recovery", "desc": "Supported sessions at your own pace."},
            {"title": "Strength Building", "desc": "Gradually rebuilding strength and energy."},
        ],
        "faqs": [
            {"q": "When can I start after a C-section?", "a": "We begin gently with your doctor's clearance, honouring your healing."},
            {"q": "Will this help with core strength?", "a": "Yes, safe core and pelvic floor recovery is a key focus."},
            {"q": "How long does recovery take?", "a": "Every body is different — we support you for as long as you need."},
        ],
    },
    {
        "slug": "baby-care-consultation",
        "title": "Baby Care Consultation",
        "icon": "Stethoscope",
        "image": "baby_care",
        "tagline": "Trusted answers when you need them",
        "short_description": "One-on-one consultations addressing your specific questions about your baby's care and development.",
        "hero_description": "From routines to milestones, our consultations give you clear, caring answers tailored to your baby.",
        "story": "Every baby is different, and every parent has questions. Our baby care consultations offer personalised, one-on-one guidance on whatever matters most to you — feeding, sleep, routines, development, or daily care. With warmth and expertise, we replace uncertainty with confidence so you can enjoy your baby's precious early days.",
        "benefits": [
            "Personalised answers to your questions",
            "Guidance on routines and development",
            "Reassurance from caring experts",
            "Confidence in everyday baby care",
        ],
        "who_for": [
            "Parents with specific care questions",
            "First-time parents seeking reassurance",
            "Families navigating new milestones",
            "Caregivers wanting expert guidance",
        ],
        "process": [
            {"title": "Share Your Questions", "desc": "Tell us what's on your mind."},
            {"title": "Focused Consultation", "desc": "Personalised, expert guidance one-on-one."},
            {"title": "Action Plan", "desc": "Clear, practical steps to follow."},
            {"title": "Follow-up", "desc": "Support as your baby grows and changes."},
        ],
        "faqs": [
            {"q": "Are consultations online?", "a": "Yes, consultations are available both online and in person."},
            {"q": "How long is a session?", "a": "Sessions typically last 45-60 minutes, focused on your needs."},
            {"q": "Can I ask about multiple topics?", "a": "Of course — bring all your questions to the session."},
        ],
    },
]

BLOG_CATEGORIES = [
    "Pregnancy Care", "Garbh Sanskar", "Motherhood", "Parenting", "Baby Care",
    "Pregnancy Yoga", "Nutrition", "Emotional Wellness", "Postpartum Recovery",
]

BLOGS = [
    {
        "slug": "nurturing-bond-garbh-sanskar",
        "title": "Nurturing the Bond: A Gentle Introduction to Garbh Sanskar",
        "category": "Garbh Sanskar",
        "tags": ["garbh sanskar", "bonding", "meditation"],
        "author": "Dr. Ananya Mehta",
        "author_role": "Garbh Sanskar Specialist",
        "reading_time": 6,
        "featured": True,
        "image": "garbh_sanskar",
        "excerpt": "Discover how the ancient practice of Garbh Sanskar nurtures your baby's well-being and deepens the bond between mother and child.",
        "content": "Garbh Sanskar is rooted in the belief that a child's journey of learning and feeling begins long before birth. From the soothing rhythm of music to the calm of meditation, every mindful moment shapes the emotional world your baby is growing into.\n\nBegin with gentle daily rituals — a few minutes of deep breathing, soft classical music, and loving affirmations spoken to your bump. These simple practices flood your body with calm and create a sense of safety your baby can feel.\n\nReading aloud, spending time in nature, and surrounding yourself with positivity are all part of this beautiful tradition. The goal is not perfection but presence: showing up each day with love and intention.\n\nAs you weave these rituals into your routine, you may notice a deeper sense of peace and connection. That is the heart of Garbh Sanskar — a pregnancy filled not just with anticipation, but with profound, mindful love.",
    },
    {
        "slug": "gentle-prenatal-yoga-poses",
        "title": "Five Gentle Prenatal Yoga Poses for Every Trimester",
        "category": "Pregnancy Yoga",
        "tags": ["yoga", "movement", "wellness"],
        "author": "Kavita Sharma",
        "author_role": "Certified Yoga Instructor",
        "reading_time": 5,
        "featured": True,
        "image": "yoga",
        "excerpt": "Stay strong, flexible, and centred with these safe prenatal yoga poses you can practise at home.",
        "content": "Prenatal yoga is one of the kindest gifts you can give your changing body. These gentle poses ease discomfort, build strength for birth, and keep you connected to your breath.\n\nStart with Cat-Cow to soothe back tension, moving slowly with your breath. Follow with a supported Wide-Legged Child's Pose to open the hips and invite calm.\n\nGentle Side Stretches create space for your growing belly, while a supported Squat builds the strength you'll lean on during labour. Finish with calm seated breathing, hands resting on your bump.\n\nAlways move within comfort, avoid deep twists, and listen to your body. When practised with care — ideally under certified guidance — yoga becomes a daily ritual of strength and serenity.",
    },
    {
        "slug": "fourth-trimester-mother-care",
        "title": "The Fourth Trimester: Why Mothers Need Care Too",
        "category": "Postpartum Recovery",
        "tags": ["postpartum", "recovery", "self-care"],
        "author": "Dr. Ritu Kapoor",
        "author_role": "Postnatal Care Expert",
        "reading_time": 7,
        "featured": False,
        "image": "mother_care",
        "excerpt": "The weeks after birth are a time of profound change. Here's how to honour your own recovery and well-being.",
        "content": "We celebrate the arrival of a baby, but the mother's recovery deserves equal tenderness. The fourth trimester — those first weeks after birth — is a season of healing, adjustment, and immense change.\n\nRest is not a luxury; it is medicine. Allow yourself to slow down, accept help, and release the pressure to 'bounce back'. Your body has done something extraordinary.\n\nNourishing food, warm fluids, and gentle movement support physical recovery, while honest conversations and emotional check-ins protect your mental well-being. It is okay to ask for support.\n\nSurround yourself with people and practices that hold you. When a mother is cared for, she can care for her baby from a place of strength, not depletion. You matter, too.",
    },
    {
        "slug": "soothing-baby-massage-ritual",
        "title": "The Soothing Ritual of Indian Baby Massage",
        "category": "Baby Care",
        "tags": ["baby massage", "bonding", "tradition"],
        "author": "Meera Iyer",
        "author_role": "Infant Care Specialist",
        "reading_time": 5,
        "featured": False,
        "image": "baby_massage",
        "excerpt": "Explore the time-honoured tradition of malish and how loving touch supports your baby's growth and sleep.",
        "content": "For generations, Indian families have practised malish — the gentle art of baby massage. Far more than routine, it is a daily ritual of love that nurtures your baby's body and your bond.\n\nChoose a warm, calm space and a gentle, baby-safe oil. Begin with soft, slow strokes on the legs, moving up to the arms, chest, and back, always watching your baby's cues.\n\nMassage supports circulation, digestion, and deeper sleep, while the rhythmic touch releases calming hormones for you both. Many babies sleep more soundly after a soothing massage and warm bath.\n\nKeep sessions short and joyful, stopping whenever your baby signals they've had enough. Over time, this tender ritual becomes a cherished part of your day — and a language of love between you.",
    },
    {
        "slug": "nourishing-pregnancy-nutrition",
        "title": "Nourishing Two: Simple Nutrition for a Healthy Pregnancy",
        "category": "Nutrition",
        "tags": ["nutrition", "pregnancy", "health"],
        "author": "Dr. Sneha Reddy",
        "author_role": "Prenatal Nutritionist",
        "reading_time": 6,
        "featured": False,
        "image": "wellness_program",
        "excerpt": "Eating well in pregnancy doesn't have to be complicated. Here are gentle, nourishing principles to guide you.",
        "content": "Pregnancy nutrition is about nourishment, not restriction. Your body needs steady, wholesome fuel to support both you and your growing baby.\n\nBuild meals around colourful vegetables, whole grains, lentils, and good fats. Traditional Indian foods like dal, seasonal vegetables, ghee, and nuts offer beautifully balanced nourishment.\n\nStay hydrated, eat small frequent meals to ease nausea, and include iron- and calcium-rich foods. Listen to your body's hunger and fullness — it is wise.\n\nAbove all, be gentle with yourself. A nourishing pregnancy diet is one built on consistency and kindness, not perfection. When in doubt, seek personalised guidance tailored to your needs.",
    },
    {
        "slug": "emotional-wellness-new-parents",
        "title": "Holding Space: Emotional Wellness for New Parents",
        "category": "Emotional Wellness",
        "tags": ["emotional wellness", "mental health", "parenting"],
        "author": "Dr. Ananya Mehta",
        "author_role": "Family Counsellor",
        "reading_time": 6,
        "featured": False,
        "image": "emotional_wellness",
        "excerpt": "Parenthood brings a wave of emotions. Learn how to care for your mental well-being through the transition.",
        "content": "Becoming a parent stirs emotions we don't always expect — overwhelming love alongside exhaustion, joy beside worry. All of it is valid.\n\nGive yourself permission to feel without judgement. Naming your emotions, talking openly with a partner or trusted person, and accepting help are powerful acts of self-care.\n\nSmall daily practices — a few quiet breaths, a short walk, a moment of stillness — help regulate the nervous system and restore balance. You cannot pour from an empty cup.\n\nIf feelings of sadness or anxiety persist, reach out for support. Seeking help is a sign of strength, not weakness. Caring for your emotional health is one of the greatest gifts you can give your family.",
    },
]

TESTIMONIALS = [
    {"name": "Priya Sharma", "role": "Mother of a newborn", "location": "Mumbai", "rating": 5,
     "text": "Sparsh Pehla held my hand through my entire pregnancy. The Garbh Sanskar sessions brought me so much peace, and I felt truly cared for at every step.", "image": "about"},
    {"name": "Anjali & Rohan Verma", "role": "First-time parents", "location": "Pune", "rating": 5,
     "text": "The family counselling sessions transformed how we communicate. We entered parenthood feeling united and prepared, thanks to their warmth and wisdom.", "image": "family_counselling"},
    {"name": "Neha Gupta", "role": "Mother of two", "location": "Delhi", "rating": 5,
     "text": "The prenatal yoga classes were a sanctuary. My instructor was so attentive and certified — I felt safe, strong, and calm right up to my delivery.", "image": "yoga"},
    {"name": "Sneha Patel", "role": "New mother", "location": "Ahmedabad", "rating": 5,
     "text": "Their lactation guidance saved my breastfeeding journey. Patient, kind, and never judgemental. I will be forever grateful for their support.", "image": "lactation"},
    {"name": "Divya Nair", "role": "Mother of a 6-month-old", "location": "Bangalore", "rating": 5,
     "text": "The baby massage workshop was beautiful. My little one sleeps so much better now, and those quiet bonding moments are the best part of my day.", "image": "baby_massage"},
    {"name": "Meena Iyer", "role": "Mother", "location": "Chennai", "rating": 5,
     "text": "The postpartum recovery guidance helped me heal gently and feel like myself again. They cared for me as much as everyone cared for the baby.", "image": "postpartum"},
]

FAQS = [
    {"q": "What services does Sparsh Pehla offer?", "a": "We offer a complete maternity and parenting wellness ecosystem — from Garbh Sanskar, prenatal yoga, and family counselling to baby massage, lactation guidance, postpartum recovery, and more."},
    {"q": "Are your instructors and counsellors certified?", "a": "Yes. Our yoga is led by a government-certified instructor, and all our specialists are experienced, qualified professionals in their fields."},
    {"q": "Do you offer online sessions?", "a": "Many of our services — including counselling, consultations, and guidance sessions — are available both in person and online for your convenience."},
    {"q": "When should I begin a programme?", "a": "It's never too early or too late. Whether you're planning, expecting, or already a parent, we tailor our support to wherever you are in your journey."},
    {"q": "Can my partner or family be involved?", "a": "Absolutely. We warmly encourage partners, grandparents, and caregivers to participate — parenthood is a family journey."},
    {"q": "How do I book a consultation?", "a": "Simply use our 'Book Consultation' page or contact form, and our team will reach out to arrange a time that suits you."},
]

GALLERY = [
    {"title": "A Mother's Glow", "category": "Maternity", "image": "hero"},
    {"title": "Tiny Beginnings", "category": "Newborn", "image": "newborn"},
    {"title": "Breath & Balance", "category": "Yoga", "image": "yoga"},
    {"title": "The Healing Touch", "category": "Baby Care", "image": "baby_massage"},
    {"title": "Captured Forever", "category": "Photography", "image": "photography"},
    {"title": "Tender Moments", "category": "Bonding", "image": "intro"},
    {"title": "Together in Love", "category": "Family", "image": "gallery1"},
    {"title": "Little Hands", "category": "Newborn", "image": "gallery2"},
    {"title": "Pure Joy", "category": "Motherhood", "image": "gallery3"},
    {"title": "Quiet Anticipation", "category": "Maternity", "image": "gallery4"},
    {"title": "Nourishing Care", "category": "Wellness", "image": "lactation"},
    {"title": "Gentle Recovery", "category": "Postpartum", "image": "postpartum"},
]

# Fallback stock URLs used if an AI-generated image is not yet available
MEDIA_FALLBACKS = {
    "hero": "https://images.pexels.com/photos/3737599/pexels-photo-3737599.jpeg",
    "intro": "https://images.pexels.com/photos/4101057/pexels-photo-4101057.jpeg",
    "about": "https://images.pexels.com/photos/3984358/pexels-photo-3984358.jpeg",
    "family_counselling": "https://images.pexels.com/photos/4546122/pexels-photo-4546122.jpeg",
    "garbh_sanskar": "https://images.pexels.com/photos/3759659/pexels-photo-3759659.jpeg",
    "yoga": "https://images.pexels.com/photos/13849185/pexels-photo-13849185.jpeg",
    "pre_shopping": "https://images.pexels.com/photos/1648377/pexels-photo-1648377.jpeg",
    "photography": "https://images.pexels.com/photos/2100371/pexels-photo-2100371.jpeg",
    "baby_massage": "https://images.pexels.com/photos/3933250/pexels-photo-3933250.jpeg",
    "wellness_program": "https://images.unsplash.com/photo-1564545801690-85554cbfe500?q=85&w=1200",
    "mother_care": "https://images.pexels.com/photos/4473864/pexels-photo-4473864.jpeg",
    "newborn": "https://images.pexels.com/photos/3933281/pexels-photo-3933281.jpeg",
    "emotional_wellness": "https://images.pexels.com/photos/3771069/pexels-photo-3771069.jpeg",
    "parenting_workshop": "https://images.pexels.com/photos/8088495/pexels-photo-8088495.jpeg",
    "lactation": "https://images.pexels.com/photos/4101056/pexels-photo-4101056.jpeg",
    "postpartum": "https://images.pexels.com/photos/3984353/pexels-photo-3984353.jpeg",
    "baby_care": "https://images.pexels.com/photos/3933027/pexels-photo-3933027.jpeg",
    "gallery1": "https://images.pexels.com/photos/1556652/pexels-photo-1556652.jpeg",
    "gallery2": "https://images.pexels.com/photos/3845457/pexels-photo-3845457.jpeg",
    "gallery3": "https://images.pexels.com/photos/1973270/pexels-photo-1973270.jpeg",
    "gallery4": "https://images.pexels.com/photos/3737599/pexels-photo-3737599.jpeg",
    "cta": "https://images.pexels.com/photos/4226215/pexels-photo-4226215.jpeg",
}
